name: checkout

on:
  workflow_call:
    inputs:
      trigger-reusable: {}

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Message
        run: echo "Hello from reusable workflow!"
