name: checkout

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
             echo " hello world  "

      
