name: Reusable Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print Message
        run: echo "Hello from reusable workflow!"
